version: '3.8'

services:
  website:
    image: labicon/website:latest
    container_name: website
    restart: unless-stopped
    ports:
      - "4004:4004"
    environment:
      - PORT=4004
    volumes:
      - ./app:/app