name: Deploy to production

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone the project into the remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/website

            rm -rf app

            git clone git@github.com:${{ github.repository }}.git ./app

            cp /home/deploy/website/.env.prod /home/deploy/website/app/.env
            cd /home/deploy/website/app

            docker build --network=host -t ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest .

            docker stop website
            docker rm website

            docker run --network=host -d --name website labicon/website

            docker image prune -af --force